# 构建阶段
FROM golang:1.24.1 as builder

WORKDIR /app/rouletteserv
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o roulette-rng .

# 运行阶段
FROM alpine:3.21.3

WORKDIR /app/rouletteserv
COPY --from=builder /app/rouletteserv/roulette-rng .

# 设置默认环境变量
ENV PORT=50000

EXPOSE $PORT

CMD ["./roulette-rng", "-mode", "rng", "-port", "50000"]