// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/gameLogic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Column
type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_proto_gameLogic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// TestBackendRequest - test input
type TestBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestBackendRequest) Reset() {
	*x = TestBackendRequest{}
	mi := &file_proto_gameLogic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBackendRequest) ProtoMessage() {}

func (x *TestBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestBackendRequest.ProtoReflect.Descriptor instead.
func (*TestBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{1}
}

func (x *TestBackendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TestBackendReply - test output
type TestBackendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestBackendReply) Reset() {
	*x = TestBackendReply{}
	mi := &file_proto_gameLogic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestBackendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBackendReply) ProtoMessage() {}

func (x *TestBackendReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestBackendReply.ProtoReflect.Descriptor instead.
func (*TestBackendReply) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{2}
}

func (x *TestBackendReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

// GameScene
type GameScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Column              `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`             // 列
	Indexes       []int32                `protobuf:"varint,2,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`   // 轮子索引
	ValidRow      []int32                `protobuf:"varint,3,rep,packed,name=validRow,proto3" json:"validRow,omitempty"` // 有效的行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameScene) Reset() {
	*x = GameScene{}
	mi := &file_proto_gameLogic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameScene) ProtoMessage() {}

func (x *GameScene) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameScene.ProtoReflect.Descriptor instead.
func (*GameScene) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{3}
}

func (x *GameScene) GetValues() []*Column {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GameScene) GetIndexes() []int32 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *GameScene) GetValidRow() []int32 {
	if x != nil {
		return x.ValidRow
	}
	return nil
}

// GameConfig
type GameConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ver           string                 `protobuf:"bytes,6,opt,name=ver,proto3" json:"ver,omitempty"`
	CoreVer       string                 `protobuf:"bytes,7,opt,name=coreVer,proto3" json:"coreVer,omitempty"`
	DefaultScene  *GameScene             `protobuf:"bytes,8,opt,name=defaultScene,proto3" json:"defaultScene,omitempty"`
	Data          string                 `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_proto_gameLogic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{4}
}

func (x *GameConfig) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *GameConfig) GetCoreVer() string {
	if x != nil {
		return x.CoreVer
	}
	return ""
}

func (x *GameConfig) GetDefaultScene() *GameScene {
	if x != nil {
		return x.DefaultScene
	}
	return nil
}

func (x *GameConfig) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// RequestConfig
type RequestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConfig) Reset() {
	*x = RequestConfig{}
	mi := &file_proto_gameLogic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConfig) ProtoMessage() {}

func (x *RequestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConfig.ProtoReflect.Descriptor instead.
func (*RequestConfig) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{5}
}

// PlayerState
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        *anypb.Any             `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       *anypb.Any             `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_gameLogic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPublic() *anypb.Any {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *PlayerState) GetPrivate() *anypb.Any {
	if x != nil {
		return x.Private
	}
	return nil
}

// RequestInitialize
type RequestInitialize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInitialize) Reset() {
	*x = RequestInitialize{}
	mi := &file_proto_gameLogic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInitialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInitialize) ProtoMessage() {}

func (x *RequestInitialize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInitialize.ProtoReflect.Descriptor instead.
func (*RequestInitialize) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{7}
}

type Stake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinBet       int64                  `protobuf:"varint,1,opt,name=coinBet,proto3" json:"coinBet,omitempty"`
	CashBet       int64                  `protobuf:"varint,2,opt,name=cashBet,proto3" json:"cashBet,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stake) Reset() {
	*x = Stake{}
	mi := &file_proto_gameLogic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stake) ProtoMessage() {}

func (x *Stake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stake.ProtoReflect.Descriptor instead.
func (*Stake) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{8}
}

func (x *Stake) GetCoinBet() int64 {
	if x != nil {
		return x.CoinBet
	}
	return 0
}

func (x *Stake) GetCashBet() int64 {
	if x != nil {
		return x.CashBet
	}
	return 0
}

func (x *Stake) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// RequestPlay - play input parameters for the game
type RequestPlay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerState   *PlayerState           `protobuf:"bytes,1,opt,name=playerState,proto3" json:"playerState,omitempty"`
	Cheat         string                 `protobuf:"bytes,2,opt,name=cheat,proto3" json:"cheat,omitempty"`
	Stake         *Stake                 `protobuf:"bytes,3,opt,name=stake,proto3" json:"stake,omitempty"`
	ClientParams  string                 `protobuf:"bytes,4,opt,name=clientParams,proto3" json:"clientParams,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPlay) Reset() {
	*x = RequestPlay{}
	mi := &file_proto_gameLogic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPlay) ProtoMessage() {}

func (x *RequestPlay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPlay.ProtoReflect.Descriptor instead.
func (*RequestPlay) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{9}
}

func (x *RequestPlay) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

func (x *RequestPlay) GetCheat() string {
	if x != nil {
		return x.Cheat
	}
	return ""
}

func (x *RequestPlay) GetStake() *Stake {
	if x != nil {
		return x.Stake
	}
	return nil
}

func (x *RequestPlay) GetClientParams() string {
	if x != nil {
		return x.ClientParams
	}
	return ""
}

func (x *RequestPlay) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// RngInfo - rng infomation
type RngInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bits          int32                  `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	Range         int32                  `protobuf:"varint,2,opt,name=range,proto3" json:"range,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RngInfo) Reset() {
	*x = RngInfo{}
	mi := &file_proto_gameLogic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RngInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RngInfo) ProtoMessage() {}

func (x *RngInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RngInfo.ProtoReflect.Descriptor instead.
func (*RngInfo) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{10}
}

func (x *RngInfo) GetBits() int32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *RngInfo) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *RngInfo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// PlayResult - result for play
type PlayResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurGameMod      string                 `protobuf:"bytes,1,opt,name=curGameMod,proto3" json:"curGameMod,omitempty"`           // 当前游戏模块，一般是 bg、fg 等等
	CurGameModParam *anypb.Any             `protobuf:"bytes,2,opt,name=curGameModParam,proto3" json:"curGameModParam,omitempty"` // 这个是游戏参数，每个游戏不一样，保存不同游戏的特殊数据
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayResult) Reset() {
	*x = PlayResult{}
	mi := &file_proto_gameLogic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResult) ProtoMessage() {}

func (x *PlayResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResult.ProtoReflect.Descriptor instead.
func (*PlayResult) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{11}
}

func (x *PlayResult) GetCurGameMod() string {
	if x != nil {
		return x.CurGameMod
	}
	return ""
}

func (x *PlayResult) GetCurGameModParam() *anypb.Any {
	if x != nil {
		return x.CurGameModParam
	}
	return nil
}

// GameResult - game result
//
//	每个game round的结算数据
type GameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinWin       int64                  `protobuf:"varint,1,opt,name=coinWin,proto3" json:"coinWin,omitempty"`      // 线注的倍数
	CashWin       int64                  `protobuf:"varint,2,opt,name=cashWin,proto3" json:"cashWin,omitempty"`      // 实际的赢得
	ClientData    *PlayResult            `protobuf:"bytes,3,opt,name=clientData,proto3" json:"clientData,omitempty"` // 局面数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResult) Reset() {
	*x = GameResult{}
	mi := &file_proto_gameLogic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResult) ProtoMessage() {}

func (x *GameResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResult.ProtoReflect.Descriptor instead.
func (*GameResult) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{12}
}

func (x *GameResult) GetCoinWin() int64 {
	if x != nil {
		return x.CoinWin
	}
	return 0
}

func (x *GameResult) GetCashWin() int64 {
	if x != nil {
		return x.CashWin
	}
	return 0
}

func (x *GameResult) GetClientData() *PlayResult {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// ReplyPlay - play output parameters for the game
type ReplyPlay struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RandomNumbers     []*RngInfo             `protobuf:"bytes,1,rep,name=randomNumbers,proto3" json:"randomNumbers,omitempty"`
	PlayerState       *PlayerState           `protobuf:"bytes,2,opt,name=playerState,proto3" json:"playerState,omitempty"`
	Finished          bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	Results           []*GameResult          `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	NextCommands      []string               `protobuf:"bytes,5,rep,name=nextCommands,proto3" json:"nextCommands,omitempty"`
	NextCommandParams []string               `protobuf:"bytes,7,rep,name=nextCommandParams,proto3" json:"nextCommandParams,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplyPlay) Reset() {
	*x = ReplyPlay{}
	mi := &file_proto_gameLogic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyPlay) ProtoMessage() {}

func (x *ReplyPlay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameLogic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyPlay.ProtoReflect.Descriptor instead.
func (*ReplyPlay) Descriptor() ([]byte, []int) {
	return file_proto_gameLogic_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyPlay) GetRandomNumbers() []*RngInfo {
	if x != nil {
		return x.RandomNumbers
	}
	return nil
}

func (x *ReplyPlay) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

func (x *ReplyPlay) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ReplyPlay) GetResults() []*GameResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReplyPlay) GetNextCommands() []string {
	if x != nil {
		return x.NextCommands
	}
	return nil
}

func (x *ReplyPlay) GetNextCommandParams() []string {
	if x != nil {
		return x.NextCommandParams
	}
	return nil
}

var File_proto_gameLogic_proto protoreflect.FileDescriptor

const file_proto_gameLogic_proto_rawDesc = "" +
	"\n" +
	"\x15proto/gameLogic.proto\x12\x06sgc7pb\x1a\x19google/protobuf/any.proto\" \n" +
	"\x06Column\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\".\n" +
	"\x12TestBackendRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x10TestBackendReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"i\n" +
	"\tGameScene\x12&\n" +
	"\x06values\x18\x01 \x03(\v2\x0e.sgc7pb.ColumnR\x06values\x12\x18\n" +
	"\aindexes\x18\x02 \x03(\x05R\aindexes\x12\x1a\n" +
	"\bvalidRow\x18\x03 \x03(\x05R\bvalidRow\"\x83\x01\n" +
	"\n" +
	"GameConfig\x12\x10\n" +
	"\x03ver\x18\x06 \x01(\tR\x03ver\x12\x18\n" +
	"\acoreVer\x18\a \x01(\tR\acoreVer\x125\n" +
	"\fdefaultScene\x18\b \x01(\v2\x11.sgc7pb.GameSceneR\fdefaultScene\x12\x12\n" +
	"\x04data\x18\v \x01(\tR\x04data\"\x0f\n" +
	"\rRequestConfig\"k\n" +
	"\vPlayerState\x12,\n" +
	"\x06public\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06public\x12.\n" +
	"\aprivate\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\aprivate\"\x13\n" +
	"\x11RequestInitialize\"W\n" +
	"\x05Stake\x12\x18\n" +
	"\acoinBet\x18\x01 \x01(\x03R\acoinBet\x12\x18\n" +
	"\acashBet\x18\x02 \x01(\x03R\acashBet\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xbd\x01\n" +
	"\vRequestPlay\x125\n" +
	"\vplayerState\x18\x01 \x01(\v2\x13.sgc7pb.PlayerStateR\vplayerState\x12\x14\n" +
	"\x05cheat\x18\x02 \x01(\tR\x05cheat\x12#\n" +
	"\x05stake\x18\x03 \x01(\v2\r.sgc7pb.StakeR\x05stake\x12\"\n" +
	"\fclientParams\x18\x04 \x01(\tR\fclientParams\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"I\n" +
	"\aRngInfo\x12\x12\n" +
	"\x04bits\x18\x01 \x01(\x05R\x04bits\x12\x14\n" +
	"\x05range\x18\x02 \x01(\x05R\x05range\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"l\n" +
	"\n" +
	"PlayResult\x12\x1e\n" +
	"\n" +
	"curGameMod\x18\x01 \x01(\tR\n" +
	"curGameMod\x12>\n" +
	"\x0fcurGameModParam\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x0fcurGameModParam\"t\n" +
	"\n" +
	"GameResult\x12\x18\n" +
	"\acoinWin\x18\x01 \x01(\x03R\acoinWin\x12\x18\n" +
	"\acashWin\x18\x02 \x01(\x03R\acashWin\x122\n" +
	"\n" +
	"clientData\x18\x03 \x01(\v2\x12.sgc7pb.PlayResultR\n" +
	"clientData\"\x95\x02\n" +
	"\tReplyPlay\x125\n" +
	"\rrandomNumbers\x18\x01 \x03(\v2\x0f.sgc7pb.RngInfoR\rrandomNumbers\x125\n" +
	"\vplayerState\x18\x02 \x01(\v2\x13.sgc7pb.PlayerStateR\vplayerState\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12,\n" +
	"\aresults\x18\x04 \x03(\v2\x12.sgc7pb.GameResultR\aresults\x12\"\n" +
	"\fnextCommands\x18\x05 \x03(\tR\fnextCommands\x12,\n" +
	"\x11nextCommandParams\x18\a \x03(\tR\x11nextCommandParams2T\n" +
	"\vTestService\x12E\n" +
	"\vTestBackend\x12\x1a.sgc7pb.TestBackendRequest\x1a\x18.sgc7pb.TestBackendReply\"\x002\xb8\x01\n" +
	"\tGameLogic\x128\n" +
	"\tgetConfig\x12\x15.sgc7pb.RequestConfig\x1a\x12.sgc7pb.GameConfig\"\x00\x12>\n" +
	"\n" +
	"initialize\x12\x19.sgc7pb.RequestInitialize\x1a\x13.sgc7pb.PlayerState\"\x00\x121\n" +
	"\x05play2\x12\x13.sgc7pb.RequestPlay\x1a\x11.sgc7pb.ReplyPlay\"\x00B'Z%gitee.com/heartfun/rouletteserv/protob\x06proto3"

var (
	file_proto_gameLogic_proto_rawDescOnce sync.Once
	file_proto_gameLogic_proto_rawDescData []byte
)

func file_proto_gameLogic_proto_rawDescGZIP() []byte {
	file_proto_gameLogic_proto_rawDescOnce.Do(func() {
		file_proto_gameLogic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gameLogic_proto_rawDesc), len(file_proto_gameLogic_proto_rawDesc)))
	})
	return file_proto_gameLogic_proto_rawDescData
}

var file_proto_gameLogic_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_gameLogic_proto_goTypes = []any{
	(*Column)(nil),             // 0: sgc7pb.Column
	(*TestBackendRequest)(nil), // 1: sgc7pb.TestBackendRequest
	(*TestBackendReply)(nil),   // 2: sgc7pb.TestBackendReply
	(*GameScene)(nil),          // 3: sgc7pb.GameScene
	(*GameConfig)(nil),         // 4: sgc7pb.GameConfig
	(*RequestConfig)(nil),      // 5: sgc7pb.RequestConfig
	(*PlayerState)(nil),        // 6: sgc7pb.PlayerState
	(*RequestInitialize)(nil),  // 7: sgc7pb.RequestInitialize
	(*Stake)(nil),              // 8: sgc7pb.Stake
	(*RequestPlay)(nil),        // 9: sgc7pb.RequestPlay
	(*RngInfo)(nil),            // 10: sgc7pb.RngInfo
	(*PlayResult)(nil),         // 11: sgc7pb.PlayResult
	(*GameResult)(nil),         // 12: sgc7pb.GameResult
	(*ReplyPlay)(nil),          // 13: sgc7pb.ReplyPlay
	(*anypb.Any)(nil),          // 14: google.protobuf.Any
}
var file_proto_gameLogic_proto_depIdxs = []int32{
	0,  // 0: sgc7pb.GameScene.values:type_name -> sgc7pb.Column
	3,  // 1: sgc7pb.GameConfig.defaultScene:type_name -> sgc7pb.GameScene
	14, // 2: sgc7pb.PlayerState.public:type_name -> google.protobuf.Any
	14, // 3: sgc7pb.PlayerState.private:type_name -> google.protobuf.Any
	6,  // 4: sgc7pb.RequestPlay.playerState:type_name -> sgc7pb.PlayerState
	8,  // 5: sgc7pb.RequestPlay.stake:type_name -> sgc7pb.Stake
	14, // 6: sgc7pb.PlayResult.curGameModParam:type_name -> google.protobuf.Any
	11, // 7: sgc7pb.GameResult.clientData:type_name -> sgc7pb.PlayResult
	10, // 8: sgc7pb.ReplyPlay.randomNumbers:type_name -> sgc7pb.RngInfo
	6,  // 9: sgc7pb.ReplyPlay.playerState:type_name -> sgc7pb.PlayerState
	12, // 10: sgc7pb.ReplyPlay.results:type_name -> sgc7pb.GameResult
	1,  // 11: sgc7pb.TestService.TestBackend:input_type -> sgc7pb.TestBackendRequest
	5,  // 12: sgc7pb.GameLogic.getConfig:input_type -> sgc7pb.RequestConfig
	7,  // 13: sgc7pb.GameLogic.initialize:input_type -> sgc7pb.RequestInitialize
	9,  // 14: sgc7pb.GameLogic.play2:input_type -> sgc7pb.RequestPlay
	2,  // 15: sgc7pb.TestService.TestBackend:output_type -> sgc7pb.TestBackendReply
	4,  // 16: sgc7pb.GameLogic.getConfig:output_type -> sgc7pb.GameConfig
	6,  // 17: sgc7pb.GameLogic.initialize:output_type -> sgc7pb.PlayerState
	13, // 18: sgc7pb.GameLogic.play2:output_type -> sgc7pb.ReplyPlay
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_gameLogic_proto_init() }
func file_proto_gameLogic_proto_init() {
	if File_proto_gameLogic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gameLogic_proto_rawDesc), len(file_proto_gameLogic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gameLogic_proto_goTypes,
		DependencyIndexes: file_proto_gameLogic_proto_depIdxs,
		MessageInfos:      file_proto_gameLogic_proto_msgTypes,
	}.Build()
	File_proto_gameLogic_proto = out.File
	file_proto_gameLogic_proto_goTypes = nil
	file_proto_gameLogic_proto_depIdxs = nil
}
