// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.23.4
// source: proto/gameLogic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_TestBackend_FullMethodName = "/sgc7pb.TestService/TestBackend"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestService - for backend testing
type TestServiceClient interface {
	TestBackend(ctx context.Context, in *TestBackendRequest, opts ...grpc.CallOption) (*TestBackendReply, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) TestBackend(ctx context.Context, in *TestBackendRequest, opts ...grpc.CallOption) (*TestBackendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestBackendReply)
	err := c.cc.Invoke(ctx, TestService_TestBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
//
// TestService - for backend testing
type TestServiceServer interface {
	TestBackend(context.Context, *TestBackendRequest) (*TestBackendReply, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) TestBackend(context.Context, *TestBackendRequest) (*TestBackendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TestBackend not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_TestBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_TestBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestBackend(ctx, req.(*TestBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgc7pb.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestBackend",
			Handler:    _TestService_TestBackend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gameLogic.proto",
}

const (
	GameLogic_GetConfig_FullMethodName  = "/sgc7pb.GameLogic/getConfig"
	GameLogic_Initialize_FullMethodName = "/sgc7pb.GameLogic/initialize"
	GameLogic_Play2_FullMethodName      = "/sgc7pb.GameLogic/play2"
)

// GameLogicClient is the client API for GameLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameLogic - GameLogic
type GameLogicClient interface {
	// getConfig - get config
	GetConfig(ctx context.Context, in *RequestConfig, opts ...grpc.CallOption) (*GameConfig, error)
	// initialize - initialize a player
	Initialize(ctx context.Context, in *RequestInitialize, opts ...grpc.CallOption) (*PlayerState, error)
	// play2 - play game v2
	Play2(ctx context.Context, in *RequestPlay, opts ...grpc.CallOption) (*ReplyPlay, error)
}

type gameLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewGameLogicClient(cc grpc.ClientConnInterface) GameLogicClient {
	return &gameLogicClient{cc}
}

func (c *gameLogicClient) GetConfig(ctx context.Context, in *RequestConfig, opts ...grpc.CallOption) (*GameConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameConfig)
	err := c.cc.Invoke(ctx, GameLogic_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameLogicClient) Initialize(ctx context.Context, in *RequestInitialize, opts ...grpc.CallOption) (*PlayerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerState)
	err := c.cc.Invoke(ctx, GameLogic_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameLogicClient) Play2(ctx context.Context, in *RequestPlay, opts ...grpc.CallOption) (*ReplyPlay, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyPlay)
	err := c.cc.Invoke(ctx, GameLogic_Play2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameLogicServer is the server API for GameLogic service.
// All implementations must embed UnimplementedGameLogicServer
// for forward compatibility.
//
// GameLogic - GameLogic
type GameLogicServer interface {
	// getConfig - get config
	GetConfig(context.Context, *RequestConfig) (*GameConfig, error)
	// initialize - initialize a player
	Initialize(context.Context, *RequestInitialize) (*PlayerState, error)
	// play2 - play game v2
	Play2(context.Context, *RequestPlay) (*ReplyPlay, error)
	mustEmbedUnimplementedGameLogicServer()
}

// UnimplementedGameLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameLogicServer struct{}

func (UnimplementedGameLogicServer) GetConfig(context.Context, *RequestConfig) (*GameConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedGameLogicServer) Initialize(context.Context, *RequestInitialize) (*PlayerState, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedGameLogicServer) Play2(context.Context, *RequestPlay) (*ReplyPlay, error) {
	return nil, status.Error(codes.Unimplemented, "method Play2 not implemented")
}
func (UnimplementedGameLogicServer) mustEmbedUnimplementedGameLogicServer() {}
func (UnimplementedGameLogicServer) testEmbeddedByValue()                   {}

// UnsafeGameLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameLogicServer will
// result in compilation errors.
type UnsafeGameLogicServer interface {
	mustEmbedUnimplementedGameLogicServer()
}

func RegisterGameLogicServer(s grpc.ServiceRegistrar, srv GameLogicServer) {
	// If the following call panics, it indicates UnimplementedGameLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameLogic_ServiceDesc, srv)
}

func _GameLogic_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogic_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicServer).GetConfig(ctx, req.(*RequestConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameLogic_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitialize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogic_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicServer).Initialize(ctx, req.(*RequestInitialize))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameLogic_Play2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPlay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLogicServer).Play2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameLogic_Play2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLogicServer).Play2(ctx, req.(*RequestPlay))
	}
	return interceptor(ctx, in, info, handler)
}

// GameLogic_ServiceDesc is the grpc.ServiceDesc for GameLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgc7pb.GameLogic",
	HandlerType: (*GameLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getConfig",
			Handler:    _GameLogic_GetConfig_Handler,
		},
		{
			MethodName: "initialize",
			Handler:    _GameLogic_Initialize_Handler,
		},
		{
			MethodName: "play2",
			Handler:    _GameLogic_Play2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gameLogic.proto",
}
