// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: proto/roulette.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"` // 下注的数字
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`          // 下注金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bet) Reset() {
	*x = Bet{}
	mi := &file_proto_roulette_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{0}
}

func (x *Bet) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *Bet) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 单个下注的输赢
type BetWin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	BetType       string                 `protobuf:"bytes,2,opt,name=betType,proto3" json:"betType,omitempty"` // 自动识别的下注类型
	Win           bool                   `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`
	WinAmount     int64                  `protobuf:"varint,4,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
	Payout        int32                  `protobuf:"varint,5,opt,name=payout,proto3" json:"payout,omitempty"` // 赔付倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetWin) Reset() {
	*x = BetWin{}
	mi := &file_proto_roulette_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetWin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetWin) ProtoMessage() {}

func (x *BetWin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetWin.ProtoReflect.Descriptor instead.
func (*BetWin) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{1}
}

func (x *BetWin) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

func (x *BetWin) GetBetType() string {
	if x != nil {
		return x.BetType
	}
	return ""
}

func (x *BetWin) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *BetWin) GetWinAmount() int64 {
	if x != nil {
		return x.WinAmount
	}
	return 0
}

func (x *BetWin) GetPayout() int32 {
	if x != nil {
		return x.Payout
	}
	return 0
}

// GameModParam
type GameModParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinningNumber int32                  `protobuf:"varint,1,opt,name=winningNumber,proto3" json:"winningNumber,omitempty"`
	Wins          []*BetWin              `protobuf:"bytes,2,rep,name=wins,proto3" json:"wins,omitempty"`
	TotalWin      int64                  `protobuf:"varint,3,opt,name=totalWin,proto3" json:"totalWin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameModParam) Reset() {
	*x = GameModParam{}
	mi := &file_proto_roulette_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameModParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameModParam) ProtoMessage() {}

func (x *GameModParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameModParam.ProtoReflect.Descriptor instead.
func (*GameModParam) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{2}
}

func (x *GameModParam) GetWinningNumber() int32 {
	if x != nil {
		return x.WinningNumber
	}
	return 0
}

func (x *GameModParam) GetWins() []*BetWin {
	if x != nil {
		return x.Wins
	}
	return nil
}

func (x *GameModParam) GetTotalWin() int64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

// 下注请求
type BetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bets          []*Bet                 `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetRequest) Reset() {
	*x = BetRequest{}
	mi := &file_proto_roulette_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRequest) ProtoMessage() {}

func (x *BetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRequest.ProtoReflect.Descriptor instead.
func (*BetRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{3}
}

func (x *BetRequest) GetBets() []*Bet {
	if x != nil {
		return x.Bets
	}
	return nil
}

var File_proto_roulette_proto protoreflect.FileDescriptor

const file_proto_roulette_proto_rawDesc = "" +
	"\n" +
	"\x14proto/roulette.proto\x12\x06sgc7pb\"7\n" +
	"\x03Bet\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\x89\x01\n" +
	"\x06BetWin\x12\x1d\n" +
	"\x03bet\x18\x01 \x01(\v2\v.sgc7pb.BetR\x03bet\x12\x18\n" +
	"\abetType\x18\x02 \x01(\tR\abetType\x12\x10\n" +
	"\x03win\x18\x03 \x01(\bR\x03win\x12\x1c\n" +
	"\twinAmount\x18\x04 \x01(\x03R\twinAmount\x12\x16\n" +
	"\x06payout\x18\x05 \x01(\x05R\x06payout\"t\n" +
	"\fGameModParam\x12$\n" +
	"\rwinningNumber\x18\x01 \x01(\x05R\rwinningNumber\x12\"\n" +
	"\x04wins\x18\x02 \x03(\v2\x0e.sgc7pb.BetWinR\x04wins\x12\x1a\n" +
	"\btotalWin\x18\x03 \x01(\x03R\btotalWin\"-\n" +
	"\n" +
	"BetRequest\x12\x1f\n" +
	"\x04bets\x18\x01 \x03(\v2\v.sgc7pb.BetR\x04betsB'Z%gitee.com/heartfun/rouletteserv/protob\x06proto3"

var (
	file_proto_roulette_proto_rawDescOnce sync.Once
	file_proto_roulette_proto_rawDescData []byte
)

func file_proto_roulette_proto_rawDescGZIP() []byte {
	file_proto_roulette_proto_rawDescOnce.Do(func() {
		file_proto_roulette_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_roulette_proto_rawDesc), len(file_proto_roulette_proto_rawDesc)))
	})
	return file_proto_roulette_proto_rawDescData
}

var file_proto_roulette_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_roulette_proto_goTypes = []any{
	(*Bet)(nil),          // 0: sgc7pb.Bet
	(*BetWin)(nil),       // 1: sgc7pb.BetWin
	(*GameModParam)(nil), // 2: sgc7pb.GameModParam
	(*BetRequest)(nil),   // 3: sgc7pb.BetRequest
}
var file_proto_roulette_proto_depIdxs = []int32{
	0, // 0: sgc7pb.BetWin.bet:type_name -> sgc7pb.Bet
	1, // 1: sgc7pb.GameModParam.wins:type_name -> sgc7pb.BetWin
	0, // 2: sgc7pb.BetRequest.bets:type_name -> sgc7pb.Bet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_roulette_proto_init() }
func file_proto_roulette_proto_init() {
	if File_proto_roulette_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_roulette_proto_rawDesc), len(file_proto_roulette_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_roulette_proto_goTypes,
		DependencyIndexes: file_proto_roulette_proto_depIdxs,
		MessageInfos:      file_proto_roulette_proto_msgTypes,
	}.Build()
	File_proto_roulette_proto = out.File
	file_proto_roulette_proto_goTypes = nil
	file_proto_roulette_proto_depIdxs = nil
}
